# Usa un'immagine di Python come base
FROM python:3.12.0-slim

# Imposta il work directory nell'applicazione
WORKDIR /app

COPY Italy.py /app/Italy.py
COPY Global.py /app/Global.py
COPY Schedule.sh /app/Schedule.sh
COPY .env /app/.env
COPY requirements.txt /app/requirements.txt


RUN pip install --no-cache-dir -r requirements.txt

RUN chmod +x Schedule.sh

CMD ["./Schedule.sh"]


